service: smart
frameworkVersion: "3"

plugins:
  - serverless-dynamodb-local
  - serverless-offline

provider:
  name: aws
  runtime: nodejs14.x
  region: us-west-2
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource:
        - arn:aws:dynamodb:us-west-2:238600808819:table/Category
        - arn:aws:dynamodb:us-west-2:238600808819:table/Product

functions:
  app:
    handler: dist/index.handler
    events:
      - httpApi:
          path: /
          method: GET
  createCategory:
    handler: dist/index.handler
    events:
      - httpApi:
          path: /categories
          method: POST
  getCategories:
    handler: dist/index.handler
    events:
      - httpApi:
          path: /categories
          method: GET
  getCategoryById:
    handler: dist/index.handler
    events:
      - httpApi:
          path: /categories/{id}
          method: GET
  updateCategory:
    handler: dist/index.handler
    events:
      - httpApi:
          path: /categories/{id}
          method: PUT
  deleteCategory:
    handler: dist/index.handler
    events:
      - httpApi:
          path: /categories/{id}
          method: DELETE
  createProduct:
    handler: dist/index.handler
    events:
      - httpApi:
          path: /products
          method: POST
  getProducts:
    handler: dist/index.handler
    events:
      - httpApi:
          path: /products
          method: GET
  getProductById:
    handler: dist/index.handler
    events:
      - httpApi:
          path: /products/{id}
          method: GET
  updateProduct:
    handler: dist/index.handler
    events:
      - httpApi:
          path: /products/{id}
          method: PUT
  deleteProduct:
    handler: dist/index.handler
    events:
      - httpApi:
          path: /products/{id}
          method: DELETE
          
resources:
  Resources:
    Category:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Category
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
    Product:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Product
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
